WebMotors/WebMotors.WebApp/Models/ErrorViewModel.cs
using System;

namespace WebMotors.WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebMotors/WebMotors.WebApp/Controllers/AnuncioWebMotorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebMotors.Domain.Entities;
using WebMotors.Infra.Data;
using WebMotors.Application.Interfaces;
using WebMotors.Application.ViewModels;
using WebMotors.Application.ViewModels.AnuncioWebMotors;

namespace WebMotors.WebApp.Controllers
{
    public class AnuncioWebMotorsController : Controller
    {
        private readonly Itb_AnuncioWebMotorsAppServices _productAppServices;

        public AnuncioWebMotorsController(Itb_AnuncioWebMotorsAppServices productAppServices)
        {
            _productAppServices = productAppServices;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            return View(await _productAppServices.Find().ConfigureAwait(true));
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id <= 0)
            {
                return NotFound();
            }

            var product = await _productAppServices.Find(id).ConfigureAwait(true);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AnuncioWebMotorsViewModel productViewModel)
        {
            if (ModelState.IsValid)
            {

                productViewModel = await _productAppServices.Insert(productViewModel).ConfigureAwait(true);

                if (productViewModel.Invalid)
                {
                    foreach (var item in productViewModel.ValidationResult.Errors)
                    {
                        ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                    }

                    return View("Create", productViewModel);
                }

            }

            return RedirectToAction(nameof(Index));
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id <= 0)
            {
                return NotFound();
            }

            var product = await _productAppServices.Find(id).ConfigureAwait(true);

            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(AnuncioWebMotorsViewModel productViewModel)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    //await _InterfaceProductApp.Update(product);


                    await _productAppServices.Update(productViewModel).ConfigureAwait(true); 

                    //if (product.Notitycoes.Any())
                    //{
                    //    foreach (var item in product.Notitycoes)
                    //    {
                    //        ModelState.AddModelError(item.NomePropriedade, item.mensagem);
                    //    }

                        return View("Edit", productViewModel);
                    //}

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await ProductExists(productViewModel.Id).ConfigureAwait(true))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(productViewModel);
        }

        private Task<bool> ProductExists(int id)
        {
            throw new NotImplementedException();
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0)
            {
                return NotFound();
            }

            var product = await _productAppServices.Find(id).ConfigureAwait(true); 
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int Id)
        {

            await _productAppServices.Delete(Id).ConfigureAwait(true);

            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> Exists(int id)
        {

            var objeto = await _productAppServices.Find(id);

            return objeto != null;
        }
    }
}

WebMotors/WebMotors.WebApp/Controllers/BaseController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebMotors.WebApp.Controllers
{
    public class BaseController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebMotors/WebMotors.WebApp/Controllers/HomeController.cs
using WebMotors.WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace WebMotors.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebMotors/WebMotors.WebApp/Views/AnuncioWebMotors/Create.cshtml
@model WebMotors.Application.ViewModels.AnuncioWebMotors.AnuncioWebMotorsViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Cadastrar</h1>

<h4>Anúncio</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Versao" class="control-label"></label>
                <input asp-for="Versao" class="form-control" />
                <span asp-validation-for="Versao" class="text-danger"></span>
            </div>
                        <div class="form-group">
                <label asp-for="Ano" class="control-label"></label>
                <input asp-for="Ano" class="form-control" />
                <span asp-validation-for="Ano" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="Quilometragem" class="control-label"></label>
                <input asp-for="Quilometragem" class="form-control" />
                <span asp-validation-for="Quilometragem" class="text-danger"></span>
            </div>
                         <div class="form-group">
                <label asp-for="Observacao" class="control-label"></label>
                <input type="text" asp-for="Observacao" class="form-control" />
                <span asp-validation-for="Observacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebMotors/WebMotors.WebApp/Views/AnuncioWebMotors/Delete.cshtml
@model WebMotors.Application.ViewModels.AnuncioWebMotors.AnuncioWebMotorsViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Deletar</h1>

<h3>Você tem certeza que deseja deletar este anúncio ?</h3>
<div>
    <h4>Anúncio</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
                <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
                <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Versao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Versao)
        </dd>
                <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ano)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ano)
        </dd>
                <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quilometragem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quilometragem)
        </dd>
                <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Observacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Observacao)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar</a>
    </form>
</div>

WebMotors/WebMotors.WebApp/Views/AnuncioWebMotors/Details.cshtml
@model WebMotors.Application.ViewModels.AnuncioWebMotors.AnuncioWebMotorsViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes</h1>

<div>
    <h4>Anúncio</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
                <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
                <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Versao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Versao)
        </dd>
                <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ano)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ano)
        </dd>
                <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quilometragem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quilometragem)
        </dd>
                <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Observacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Observacao)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Editar</a> |
    <a asp-action="Index">Voltar</a>
</div>

WebMotors/WebMotors.WebApp/Views/AnuncioWebMotors/Edit.cshtml
@model WebMotors.Application.ViewModels.AnuncioWebMotors.AnuncioWebMotorsViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Anúncio</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Versao" class="control-label"></label>
                <input asp-for="Versao" class="form-control" />
                <span asp-validation-for="Versao" class="text-danger"></span>
            </div>
                        <div class="form-group">
                <label asp-for="Ano" class="control-label"></label>
                <input asp-for="Ano" class="form-control" />
                <span asp-validation-for="Ano" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="Quilometragem" class="control-label"></label>
                <input asp-for="Quilometragem" class="form-control" />
                <span asp-validation-for="Quilometragem" class="text-danger"></span>
            </div>
                         <div class="form-group">
                <label asp-for="Observacao" class="control-label"></label>
                <input asp-for="Observacao" class="form-control" />
                <span asp-validation-for="Observacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebMotors/WebMotors.WebApp/Views/AnuncioWebMotors/Index.cshtml
@model IEnumerable<WebMotors.Application.ViewModels.AnuncioWebMotors.AnuncioWebMotorsViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Home</h1>

<p>
    <a asp-action="Create">Novo Cadastro</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Modelo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Versao)
            </th>
                        <th>
                @Html.DisplayNameFor(model => model.Ano)
            </th>
                        <th>
                @Html.DisplayNameFor(model => model.Quilometragem)
            </th>
                        <th>
                @Html.DisplayNameFor(model => model.Observacao)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Marca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Modelo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Versao)
            </td>
                        <td>
                @Html.DisplayFor(modelItem => item.Ano)
            </td>
                        <td>
                @Html.DisplayFor(modelItem => item.Quilometragem)
            </td>
                        <td>
                @Html.DisplayFor(modelItem => item.Observacao)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Deletar</a>
            </td>
        </tr>
}
    </tbody>
</table>

WebMotors/WebMotors.WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebMotors/WebMotors.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebMotors.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebMotors.WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AnuncioWebMotors" asp-action="Index">Anuncio Web Motors</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebMotors.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>